### ISSUE TITLE
Error when using `attach-index`

### ISSUE THREAD

**Issue by hadim** [izihawa/summa#150]
To make it work, I had to do the following:

- install `aiosumma` from the `master` branch of this repo (not from pypi).
- then in `aiosumma/client.py` line 77 replace `**index_engine,` by `ipfs=ipfs`

**Comment by hadim** [comment]
The indexing is now running for ~30 minutes and I don't know whether it's just slow or doing something but my network IO does not show much activity, neither CPU usage and memory usage of the docker container. Also the data folder size is stuck at a size of 150kb.

I will let it run longer and see how it goes.

**Comment by hadim** [comment]
The command used is:

```
summa-cli 0.0.0.0:8082 attach-index \
  "nexus_science" \
  --ipfs '{"cid": "xxxxxxxxxxxxxxxx"}'
```

**Comment by hadim** [comment]
Indexing failed after 40 minutes with:

```
ERROR: StatusCode.INTERNAL (json_error: missing field `unique_fields`)
```

**Comment by hadim** [comment]
I can also see a bunch of errors/warnings in the logs of the server:

```
summa_1  | 2023-01-29T01:11:02.099895Z  WARN  tokio-runtime-workers-1 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AdtyFCqDfcTgrX6hRrvEsjNaVJCTi2ipjUMEfmHm9mUMC"), num_remaining: Some(2) }
summa_1  | 2023-01-29T01:11:02.100138Z  WARN  tokio-runtime-workers-1 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AZEGjnp197VEwwJYkc8CWownvWMZdpNwtt9SW3Bht8jsi"), num_remaining: Some(2) }
summa_1  | 2023-01-29T01:12:02.222840Z  WARN tokio-runtime-workers-12 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AXdknbET1vo6TrcF4fjPLznnuotd1xpQmRA3wSeHJYQXB"), num_remaining: Some(1) }
summa_1  | 2023-01-29T01:12:02.223115Z  WARN tokio-runtime-workers-12 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AeRFBPNEg3GrKUcEG1LS4GVwqqB9HQyXxJHHa2niA6JtZ"), num_remaining: Some(1) }
summa_1  | 2023-01-29T01:13:02.276956Z  WARN tokio-runtime-workers-27 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AbfnSDGCoiFkEfHzg77rpQWrGnDXAgTjMhfv6mSXasjdd"), num_remaining: Some(0) }
summa_1  | 2023-01-29T01:13:02.277197Z  WARN tokio-runtime-workers-27 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AjNzz4fPEmp5nkwXfaZX4ewo6t6zyyuWjWsp4JbJNNUfK"), num_remaining: Some(0) }
summa_1  | 2023-01-29T01:13:49.467517Z  WARN tokio-runtime-workers-21 libp2p_quic::endpoint: Error while sending on QUIC UDP socket: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }    
summa_1  | 2023-01-29T01:13:49.467539Z  WARN tokio-runtime-workers-21 libp2p_quic::endpoint: Error while sending on QUIC UDP socket: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }    
summa_1  | 2023-01-29T01:13:49.731283Z  WARN tokio-runtime-workers-21 quinn_proto::connection: discarding possible duplicate packet
summa_1  | 2023-01-29T01:14:02.351494Z  WARN tokio-runtime-workers-19 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AdKKswvZDtigKeQXnWAmSSs8QNLZytooP1V9e1pJwPSRD"), num_remaining: Some(0) }
summa_1  | 2023-01-29T01:14:02.351716Z  WARN tokio-runtime-workers-19 iroh_p2p::node: kad bootstrap error: Timeout { peer: PeerId("1AXZYpctaKtZf427qpSq6iCHA1mr5MXMg2cEUhni2GGfjN"), num_remaining: Some(0) }
```

**Comment by ppodolsky** [comment]
Hello!
> then in aiosumma/client.py line 77 replace **index_engine, by ipfs=ipfs

Yes, syntax has been slightly changed recently. No need to hack, just change:
```
summa-cli 0.0.0.0:8082 attach-index \
  "nexus_science" \
  --ipfs '{"cid": "xxxxxxxxxxxxxxxx"}'
```
to
```
summa-cli 0.0.0.0:8082 attach-index \
  "nexus_science" \
  '{"ipfs": {"cid": "xxxxxxxxxxxxxxxx"}}'
```
Thanks for mentioning, I've fixed documentation.

> ERROR: StatusCode.INTERNAL (json_error: missing field `unique_fields`)

Means that the attaching index has been composed for older Summa versions. Nevertheless, I've fixed it and now `IndexAttributes` falls back to default values if some fields are absent. Just ensure that you are using actual versions of everything, I've updated them several minutes ago.

> iroh_p2p::node: kad bootstrap error

Comes from `libp2p`. May only guess whether your server has Internet connectivity? Could you confirm that you may connect to IPFS [bootstrap nodes](https://github.com/ipfs/go-ipfs-config/blob/master/bootstrap_peers.go#L17)? I.e `telnet 104.131.131.82 4001` shows something like `.../multistream/1.0.0` 
Anyway, you have seen the error about `unique_fields` and it means you had finally found peers who may seed your files.

"Long attach-index" indicates potential lack of seeding peers. The command only attempts to feed index files by their CID and doesn't index anything. If you are attempting to attach index over the Internet, make sure the CID is available. A good indicator of file availability is visibility through the IPFS gateway. Try accessing `https://w3s.link/ipfs/<cid>`. If the page loads, the files are visible and the issue is likely with your node's connectivity. If the files are not visible, there may be a lack of seeders.

**Comment by hadim** [comment]
Thanks. All the errors are gone now but I still have the `kad bootstrap error` + `attach-index` seems to hang forever without doing anything.

The `telnet` command works for both the host machine and within a docker container.

I also checked whether https://w3s.link/ipfs/<cid> was accessible from the host and it is.

**Comment by hadim** [comment]
Sp `summa-cli` does not returns an error except when I trigger Ctrl+C:

```
ERROR: StatusCode.INTERNAL (anyhow_error: failed to find <CID>)
```

I don't see much on the server side.

**Comment by hadim** [comment]
After re-trying multiple times, it finally worked and `attach-index` was almost instant indeed. I am now running `warmup-index` which seems to take much more time but at least I can see the data folder slowly growing. So, it seems to work.

Thanks.

**Comment by hadim** [comment]
(it would be nice to create GH release, git tag and also tag the docker images with the associated git tag if you ever have the time to do that. it makes deployment for users more robust)

**Comment by ppodolsky** [comment]
Thank you for the comprehensive feedback! I'll expand the list of bootstrap nodes and expose the peer management API soon. This will allow you to connect to desired peers through CLI. It might improve the initial performance in some cases. IPFS performance should be comparable to Iroh and hopefully, it will be improved in the near future.

Regarding tagging, it was a surprise for me that users started using Summa so soon. However, now that it has happened, I'll tag the next release and the Docker image after several stabilization patches are applied.
